services:
  psycholog-transportu:
    build:
      context: .
      dockerfile: Dockerfile
    image: psycholog-transportu:latest
    container_name: psycholog-transportu-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.psycholog.rule=Host(`psycholog-transportu-przemysl.pl`)"
      - "traefik.http.routers.psycholog.entrypoints=websecure"
      - "traefik.http.routers.psycholog.tls.certresolver=letsencrypt"
      - "traefik.http.services.psycholog.loadbalancer.server.port=3000"
#     networks:
#       - towerlights_network

# networks:
#   towerlights_network:
#     external: true
